added_project
Sigbln/Tamagochi pull request #1
Opened 2021-03-30 11:02 UTC by Sigbln

2021-03-30 11:56 UTC, corwinnn requested changes

2021-03-30 11:56 UTC, corwinnn commented on main.py
> +import os
Очень много и непонятно, разбей на файлы

2021-03-30 11:56 UTC, corwinnn commented on README.md
> ++ Скачать с гитхаба
Добавь строки комманд

2021-03-30 11:56 UTC, corwinnn commented on Pet.py
> +    @property
Не очень понял, зачем тут property

2021-03-30 11:56 UTC, corwinnn commented on main.py
> +def draw_screen():
очень много магических констант

2021-03-31 08:44 UTC, corwinnn requested changes

2021-03-31 08:44 UTC, corwinnn commented on Pet.py
> +    @property
до сих пор не понял

2021-03-31 08:44 UTC, corwinnn commented on README.md
> ++ git clone https://github.com/Sigbln/Tamagochi.git
Используй специальный маркдаун для строк кода

2021-03-31 08:44 UTC, corwinnn commented on HUD.py
> +from global_names import *
убрать * здесь и далее

2021-03-31 08:44 UTC, corwinnn commented on global_names.py
> +bg = True
в чем отличие переменных капсом и не капсом?

2021-03-31 08:44 UTC, corwinnn commented on main.py
> +def draw_screen():
стало меньше, но еще много

2021-03-31 08:44 UTC, corwinnn commented on main.py
> +def a_u_ok():
функции идут вперемешку со строками кода в main
обычно в main не больше 20 строк только кода, без объявлений новых функций, а все остальное импортится

2021-03-31 08:44 UTC, corwinnn commented on make_anims.py
> +# Делаю листы для анимации
Сделай в одну строчку

2021-03-31 08:44 UTC, corwinnn commented on saver.py
> +        kof = int((time.time() - data['time']) / (3600 * 24) * 40)
что таоке kof?
и напиши комментарий, что происходит

2021-03-31 08:44 UTC, corwinnn commented on saver.py
> +# проверея существует ли файл с сохранением и загружаю последнее сохранение
проверяет

2021-03-31 16:14 UTC, corwinnn requested changes

2021-03-31 16:14 UTC, corwinnn commented on funcs.py
> +    if global_names.pet.bot > global_names.FULL:
max()

2021-03-31 16:14 UTC, corwinnn commented on funcs.py
> +                global_names.pet.eat += 30
магические константты

2021-04-01 09:37 UTC, corwinnn requested changes

2021-04-01 09:37 UTC, corwinnn commented on README.md
> +<p><code>python main.py</code><p>
Сделай чтоб в одном блоке были

а команда cd не нужна?

2021-04-01 09:37 UTC, corwinnn commented on README.md
> +# Tamagochi MIPT student #
Добавь скрины в ридми

2021-04-01 09:37 UTC, corwinnn commented on funcs.py
> +import global_names
напиши в правильном порядке с отступами здесь и в остальных файлах

2021-04-01 09:37 UTC, corwinnn commented on funcs.py
> +    # decrease hp if stats < 0
добавь пустые строки между блоками

2021-04-01 09:37 UTC, corwinnn commented on funcs.py
> +        global_names.GAME_TIME = 540
магическая константа

2021-04-01 09:37 UTC, corwinnn commented on funcs.py
> +        global_names.GAME_TIME = 540
убери оставшиеся константы здесь и далее в других файлах тоже

2021-04-01 09:37 UTC, corwinnn commented on funcs.py
> +    elif global_names.BG:  #
#?

2021-04-01 09:37 UTC, corwinnn commented on make_anims.py
> +BG1 = [pygame.image.load(f"images/bg/{i}.gif") for i in range(48)]
можно ли здесь написать range(len(dir)), чтобы не было константы?

2021-04-01 09:37 UTC, corwinnn commented on saver.py
> +        kof = int((time.time() - data['time']) / (3600 * 24) * 40)
Переменные должны говорить о себе. Я не понимаю, что такое kof. Если это коэффициент, то coef хотя бы

2021-04-01 09:37 UTC, corwinnn commented on saver.py
> +        data = {'eat': global_names.pet.eat, 'bot': global_names.pet.bot,
Сделай во всех файлах либо только одинарные кавычки, либо только двойные

2021-04-06 15:10 UTC, honoody commented
Готово

2021-04-19 14:09 UTC, corwinnn commented on saver.py
> +import pickle
нарушен порядок импортов

2021-04-20 20:13 UTC, corwinnn approved these changes

2021-04-20 21:39 UTC, merged